# Using the official Node.js image as the base image
FROM node:21-bullseye

# Create and set the working directory
WORKDIR /portfolio

COPY package*.json .

RUN npm ci
RUN npx playwright install --with-deps chromium

COPY . .

CMD ["npm", "run", "ci:test"]
